'use strict';
const TWO=Math.PI*2, rnd=(a,b)=>a+Math.random()*(b-a), clamp=(x,a,b)=>Math.max(a,Math.min(b,x)), dist2=(a,b,c,d)=>(a-c)**2+(b-d)**2;
class FlightGame{
 constructor(){
  this.canvas=document.getElementById('screen');this.ctx=this.canvas.getContext('2d',{alpha:false});this.root=document.getElementById('game');
  this.ui={score:document.getElementById('score'),wave:document.getElementById('wave'),hearts:document.getElementById('hearts'),overlay:document.getElementById('overlay'),cap:document.getElementById('overlay-cap'),title:document.getElementById('overlay-title'),text:document.getElementById('overlay-text'),foot:document.getElementById('overlay-foot'),start:document.getElementById('start'),burst:document.getElementById('barrage'),burstTime:document.getElementById('burst-time'),pause:document.getElementById('pause'),sound:document.getElementById('sound')};
  this.W=480;this.H=800;this.time=0;this.mode='title';this.soundOn=false;this.audio=null;this.best=0;try{this.best=+(localStorage.getItem('stellar-flock-best')||0)}catch(_){}
  this.stars=Array.from({length:135},()=>({x:rnd(0,480),y:Math.random(),r:rnd(.3,1.6),speed:rnd(.06,.25),light:rnd(.15,.95)}));
  this.bgDust=Array.from({length:18},()=>({x:rnd(0,480),y:Math.random(),r:rnd(16,75),s:rnd(.7,2.8)}));
  this.enemies=[];this.missiles=[];this.enemyShots=[];this.particles=[];this.rings=[];this.textPop=[];this.player={x:240,tx:240,y:700,invul:0};this.keys={};this.pointer=false;this.jolt=0;this.waveFlash=0;this.hitFlash=0;this.nextWaveTimer=0;
  this.score=0;this.lives=3;this.wave=1;this.combo=0;this.comboTimer=0;this.fireTimer=.2;this.diveTimer=1;this.burstCD=0;this.missileSerial=0;this.lastHUD='';
  this.bind();this.resize();this.setupWave();this.last=performance.now();requestAnimationFrame(this.loop.bind(this));
 }
 resize(){const r=this.root.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);this.H=480*r.height/r.width;this.canvas.width=Math.round(r.width*d);this.canvas.height=Math.round(r.height*d);this.ctx.setTransform(this.canvas.width/480,0,0,this.canvas.height/this.H,0,0);this.player.y=this.H-105;this.player.x=clamp(this.player.x,34,446);this.player.tx=clamp(this.player.tx,34,446);}
 bind(){addEventListener('resize',()=>this.resize());document.getElementById('start').onclick=()=>this.mode==='paused'?this.togglePause():this.start();this.ui.burst.onclick=e=>{e.stopPropagation();this.burst()};this.ui.pause.onclick=()=>this.togglePause();this.ui.sound.onclick=()=>{this.soundOn=!this.soundOn;this.ui.sound.textContent=this.soundOn?'SOUND ON':'SOUND OFF';if(this.soundOn)this.beep(650,.08,.025)};
  const move=e=>{const r=this.canvas.getBoundingClientRect();this.player.tx=clamp((e.clientX-r.left)/r.width*480,32,448)};
  this.canvas.addEventListener('pointerdown',e=>{this.pointer=true;this.canvas.setPointerCapture(e.pointerId);move(e)});this.canvas.addEventListener('pointermove',e=>{if(this.pointer||e.pointerType==='mouse')move(e)});this.canvas.addEventListener('pointerup',()=>this.pointer=false);this.canvas.addEventListener('pointercancel',()=>this.pointer=false);
  addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight',' ','KeyA','KeyD','KeyP','Escape','Enter'].includes(e.code))e.preventDefault();this.keys[e.code]=true;if(e.repeat)return;if(e.code==='Space')this.burst();if(e.code==='KeyP'||e.code==='Escape')this.togglePause();if(e.code==='Enter'&&this.mode!=='playing')this.start()});addEventListener('keyup',e=>{this.keys[e.code]=false});addEventListener('blur',()=>{if(this.mode==='playing')this.togglePause()});
 }
 beep(f,d=.06,v=.045){if(!this.soundOn)return;try{this.audio ||= new(window.AudioContext||window.webkitAudioContext)();let o=this.audio.createOscillator(),g=this.audio.createGain();o.type='triangle';o.frequency.setValueAtTime(f,this.audio.currentTime);o.frequency.exponentialRampToValueAtTime(f*.55,this.audio.currentTime+d);g.gain.setValueAtTime(v,this.audio.currentTime);g.gain.exponentialRampToValueAtTime(.0001,this.audio.currentTime+d);o.connect(g).connect(this.audio.destination);o.start();o.stop(this.audio.currentTime+d)}catch(_){}}
 start(){this.mode='playing';this.ui.overlay.classList.add('hidden');this.ui.pause.textContent='Ⅱ PAUSE';this.score=0;this.wave=1;this.lives=3;this.combo=0;this.comboTimer=0;this.missiles=[];this.enemyShots=[];this.particles=[];this.rings=[];this.player.x=240;this.player.tx=240;this.player.invul=2;this.burstCD=0;this.setupWave();this.syncHUD()}
 togglePause(){if(this.mode==='playing'){this.mode='paused';this.showOverlay('SIGNAL LOST','PAUSED','一時停止中。<br>機体の位置はそのままです。','RESUME MISSION','ESC / P で再開');this.ui.pause.textContent='▶ RESUME'}else if(this.mode==='paused'){this.mode='playing';this.ui.overlay.classList.add('hidden');this.ui.pause.textContent='Ⅱ PAUSE'}}
 showOverlay(cap,title,desc,action,foot){this.ui.cap.textContent=cap;this.ui.title.innerHTML=title;this.ui.text.innerHTML=desc;this.ui.start.textContent=action;this.ui.foot.innerHTML=foot;this.ui.overlay.classList.remove('hidden')}
 setupWave(){this.enemies=[];const rows=Math.min(5,3+Math.floor(this.wave/2)),cols=7;for(let r=0;r<rows;r++)for(let c=0;c<cols;c++){const variant=r===0?2:r===1?1:0;this.enemies.push({id:this.wave*100+r*cols+c,col:c,row:r,slotX:240+(c-3)*53,slotY:159+r*51,x:240+(c-3)*53,y:159+r*51,phase:rnd(0,6.28),variant,hp:variant===2&&this.wave>1?2:1,state:'formation',diveT:0,diveLen:0,side:1,shot:false,alive:true});}this.diveTimer=1.25;this.nextWaveTimer=0;this.waveFlash=2;this.syncHUD()}
 beginDive(e){e.state='dive';e.diveT=0;e.diveLen=rnd(2.9,3.7);e.diveX=e.x;e.diveY=e.y;e.side=e.x>240?-1:1;e.shot=false;}
 enemyPos(e,dt){if(e.state==='formation'){e.x=e.slotX+Math.sin(this.time*.78)*20+Math.sin(this.time*1.7+e.phase)*2.5;e.y=e.slotY+Math.sin(this.time*1.5+e.col*.6)*5;return;}e.diveT+=dt;const p=e.diveT/e.diveLen;if(p>=1){e.state='formation';return}
   if(p<.59){const q=p/.59;e.y=e.diveY+(this.H+85-e.diveY)*(q*q*(3-2*q));e.x=clamp(e.diveX+e.side*(Math.sin(q*Math.PI)*115+q*75),25,455)}else{const q=(p-.59)/.41;e.y=-55+(e.slotY+55)*(q*q*(3-2*q));e.x=clamp(e.slotX+Math.sin((1-q)*Math.PI*1.3)*145*e.side,25,455)}
  if(!e.shot&&p>.14&&p<.46&&this.shootEnemy(e)){e.shot=true}
 }
 shootEnemy(e){const dx=this.player.x-e.x,dy=this.player.y-e.y,l=Math.hypot(dx,dy)||1;
  // Never fire at point-blank range: reserve enough time for a human to react and move.
  const v=Math.min(290,200+this.wave*8),secondsToHit=(l-23)/v;
  if(dy<240||secondsToHit<1.05)return false;
  this.enemyShots.push({x:e.x,y:e.y,vx:dx/l*v,vy:dy/l*v,life:4,trail:[]});return true}
 spawnMissile(target,index=0,total=1,isBurst=false){if(!target||!target.alive)return;const p=this.makeMissilePersonality(index,total,isBurst);const sx=this.player.x+(index%2?15:-15),sy=this.player.y-15;this.missiles.push({x:sx,y:sy,vx:p.side*p.launchSpeed,vy:-p.cruise,life:6,age:0,target,trail:[{x:sx,y:sy}],hue:p.hue+rnd(-7,7),burst:isBurst,personality:p});if(this.missiles.length>125)this.missiles.shift()}
 targets(){return this.enemies.filter(e=>e.alive).sort((a,b)=>(a.state==='dive'?-270:0)+(Math.abs(a.x-this.player.x)*.35+a.y*.18) - ((b.state==='dive'?-270:0)+(Math.abs(b.x-this.player.x)*.35+b.y*.18)))}
 burst(){if(this.mode!=='playing'||this.burstCD>0)return;const a=this.targets();if(!a.length)return;for(let n=0;n<12;n++)this.spawnMissile(a[n%Math.min(a.length,7)],n,12,true);this.burstCD=9;this.beep(920,.24,.07);this.jolt=Math.max(this.jolt,5);this.waveFlash=Math.max(this.waveFlash,.22);this.syncHUD()}
 impact(x,y,hue=180,count=9,scale=1){this.rings.push({x,y,r:2,life:.3,hue});for(let k=0;k<count;k++){const a=rnd(0,TWO),v=rnd(35,165)*scale;this.particles.push({x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v,life:rnd(.24,.72),max:.72,r:rnd(1.3,3.8)*scale,hue});}if(this.particles.length>300)this.particles.splice(0,this.particles.length-300)}
 hitEnemy(e){if(!e.alive)return;e.hp--;this.impact(e.x,e.y,e.variant===2?323:190,10);this.beep(e.hp?390:790,.055,.025);if(e.hp>0)return;e.alive=false;this.comboTimer=2.8;this.combo=Math.min(this.combo+1,25);const pts=(e.variant===2?220:e.variant===1?150:100)*(1+Math.floor(this.combo/5));this.score+=pts;this.textPop.push({x:e.x,y:e.y-6,t:1,text:'+'+pts});this.impact(e.x,e.y,e.variant===2?320:178,22,1.2);this.jolt=Math.max(this.jolt,4);if(this.score>this.best){this.best=this.score;try{localStorage.setItem('stellar-flock-best',this.best)}catch(_){}}this.syncHUD()}
 hitPlayer(){if(this.player.invul>0||this.mode!=='playing')return;this.lives--;this.player.invul=2.5;this.hitFlash=.6;this.jolt=13;this.impact(this.player.x,this.player.y,333,36,1.7);this.beep(180,.25,.08);this.combo=0;this.comboTimer=0;this.syncHUD();if(this.lives<=0){this.mode='gameover';this.showOverlay('MISSION COMPLETE','GAME <em>OVER</em>','SCORE: '+String(this.score).padStart(6,'0')+'<br>BEST: '+String(this.best).padStart(6,'0')+'<br>WAVE '+this.wave+' まで到達','TRY AGAIN','自動ロックオン＋追尾弾 / BURST で一斉射撃')}}
 syncHUD(){this.ui.score.textContent=String(this.score).padStart(6,'0');this.ui.wave.textContent=String(this.wave).padStart(2,'0');this.ui.hearts.textContent=('◆ '.repeat(this.lives)).trim()||'—';this.ui.burst.disabled=this.mode!=='playing'||this.burstCD>0;this.ui.burstTime.textContent=this.burstCD>0?this.burstCD.toFixed(1)+'s':'READY'}
}